### ISSUE TITLE
Must be logged into huggingface-cli for initial app launch downloads to work

### ISSUE THREAD

**Issue by nathanhere** [erew123/alltalk_tts#109]
Would be helpful to note in installation instructions.

Otherwise error occurs:

```
(C:\alltalk_tts\alltalk_environment\env) C:\alltalk_tts>start_alltalk.bat
[2024-03-06 23:59:02,974] [INFO] [real_accelerator.py:174:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-03-06 23:59:03,324] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
[AllTalk Startup] Running script.py in standalone mode
[AllTalk Startup] Coqui Public Model License
[AllTalk Startup] https://coqui.ai/cpml.txt
[AllTalk Startup] Old output wav file deletion is set to disabled.
[AllTalk Startup] Checking Model is Downloaded.
[AllTalk Startup] Downloading dvae.pth...
Traceback (most recent call last):
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\alltalk_tts\alltalk_environment\env\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001DA7EFFB410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /coqui/XTTS-v2/resolve/v2.0.2/dvae.pth?download=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DA7EFFB410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\alltalk_tts\modeldownload.py", line 143, in <module>
    download_file(url, destination)
  File "C:\alltalk_tts\modeldownload.py", line 69, in download_file
    response = requests.get(url, stream=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\alltalk_tts\alltalk_environment\env\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /coqui/XTTS-v2/resolve/v2.0.2/dvae.pth?download=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DA7EFFB410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by erew123** [comment]
Hi @nathanhere 

I absolutely agree it should be documented, however, this has never been the case historically. To test I've just installed a fresh copy and tested the `modeldownloader.py` and it went through without issue (I am not logged into huggingface in any way), so I have been unable to reproduce the issue you faced.

As far as things go, the error messages you have `socket.gaierror: [Errno 11001] getaddrinfo failed` and
`Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))` these are DNS name resolution errors (Your computer cannot resolve the internet name of huggingface.co, assumedly temporarily).

One way or another, your machine was unable to resolve the DNS address for huggingface.co, be it that it was something on your machine, your internet connection, your upstream DNS server, some filtering you have (antivirus/firewall), a blip on the internet of some kind or an issue at Huggingface or even a geographic requirement by Huggingface that you log in (I don't know if they do this). Or perhaps they are even getting DDOS attacked from a geographic location and logging into Huggingface resolves this issue by confirming its a real user whom is logged in.

Here is the actual web page it downloads the model from https://huggingface.co/coqui/XTTS-v2/tree/main and you should be able to reach it and download from there without needing to log in.

I assume you have managed to resolve the issue for now, based on the fact you said that "otherwise error occurs"?

Please let me know and if needed I can give you a few suggestions to test what could be the issue on your machine/internet connection.

**For reference here was my test** <br>



![Screenshot from 2024-03-07 09-09-11](https://github.com/erew123/alltalk_tts/assets/35898566/955b3fbf-6d3e-4236-82e3-627f131216e4)
<br>
Thanks

**Comment by nathanhere** [comment]
Hah good to know the main setup weirdness could just be me. Funny enough, being logged into huggingface-cli and using “docker compose up” with the Nvidia dockercompose file got me up and running!

**Comment by erew123** [comment]
Glad it's all sorted for you. I'll close the ticket off for now. Thanks
