### ISSUE TITLE
finetuning Step 2 missing file mel_stats.pth

### ISSUE THREAD

**Issue by rktvr** [erew123/alltalk_tts#15]
When running Step 2 of the finetuning it errors saying "mel_stats.pth" is missing:
Step 1 ran fine though.

```
[FINETUNE] Starting Step 2 - Fine-tuning the XTTS Encoder
Traceback (most recent call last):
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\extensions\alltalk_tts\finetune.py", line 817, in train_model
    config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=str(output_path), max_audio_length=max_audio_length)
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\extensions\alltalk_tts\finetune.py", line 384, in train_gpt
    model = GPTTrainer.init_from_config(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\installer_files\env\Lib\site-packages\TTS\tts\layers\xtts\trainer\gpt_trainer.py", line 500, in init_from_config
    return GPTTrainer(config)
           ^^^^^^^^^^^^^^^^^^
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\installer_files\env\Lib\site-packages\TTS\tts\layers\xtts\trainer\gpt_trainer.py", line 88, in __init__
    self.xtts.mel_stats = load_fsspec(self.args.mel_norm_file)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\installer_files\env\Lib\site-packages\TTS\utils\io.py", line 46, in load_fsspec
    with fsspec.open(
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\installer_files\env\Lib\site-packages\fsspec\core.py", line 100, in __enter__
    f = self.fs.open(self.path, mode=mode)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\installer_files\env\Lib\site-packages\fsspec\implementations\cached.py", line 417, in <lambda>
    return lambda *args, **kw: getattr(type(self), item).__get__(self)(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\installer_files\env\Lib\site-packages\fsspec\spec.py", line 1307, in open
    f = self._open(
        ^^^^^^^^^^^
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\installer_files\env\Lib\site-packages\fsspec\implementations\cached.py", line 417, in <lambda>
    return lambda *args, **kw: getattr(type(self), item).__get__(self)(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\installer_files\env\Lib\site-packages\fsspec\implementations\cached.py", line 646, in _open
    fn = self._make_local_details(path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\installer_files\env\Lib\site-packages\fsspec\implementations\cached.py", line 417, in <lambda>
    return lambda *args, **kw: getattr(type(self), item).__get__(self)(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\installer_files\env\Lib\site-packages\fsspec\implementations\cached.py", line 570, in _make_local_details
    "uid": self.fs.ukey(path),
           ^^^^^^^^^^^^^^^^^^
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\installer_files\env\Lib\site-packages\fsspec\spec.py", line 1346, in ukey
    return sha256(str(self.info(path)).encode()).hexdigest()
                      ^^^^^^^^^^^^^^^
  File "E:\oobabooga\text-generation-webui-snapshot-2023-11-19\installer_files\env\Lib\site-packages\fsspec\implementations\local.py", line 83, in info
    out = os.stat(path, follow_symlinks=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:/oobabooga/text-generation-webui-snapshot-2023-11-19/extensions/alltalk_tts/models/xttsv2_2.0.2/mel_stats.pth'
```

**Comment by erew123** [comment]
So when you get the update, your modeldownload.json file should have updated to this one https://github.com/erew123/alltalk_tts/blob/main/modeldownload.json

and when you start AllTalk (in Text-generation-webui or as a standalone) it should be downloading those extra 2x files.....

at the command prompt where you started fintuneing.py, try running `python script.py` which will start AllTalk in standalone mode and it should download the extra 2 files. Let me know if not and check your modeldownload.json is correct.

Thanks

**Comment by rktvr** [comment]
Ohh I see it in the modeldownload.json. 
Alright, means I did forget to actually run it again after updating (thought I did), sorry about that.
Just ran it and it did in fact download the models now.

**Comment by erew123** [comment]
No probs :) It should work now! Let me know if not!
