### ISSUE TITLE
Urgent nvidia.Dockerfile gives an error no module named exceptiongroup 

### ISSUE THREAD

**Issue by ehsanahmadkhan525** [erew123/alltalk_tts#180]
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 409, in main
    run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 22, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/tts_server.py", line 16, in <module>
    from fastapi import (
  File "/usr/local/lib/python3.10/dist-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/usr/local/lib/python3.10/dist-packages/fastapi/params.py", line 5, in <module>
    from fastapi.openapi.models import Example
  File "/usr/local/lib/python3.10/dist-packages/fastapi/openapi/models.py", line 4, in <module>
    from fastapi._compat import (
  File "/usr/local/lib/python3.10/dist-packages/fastapi/_compat.py", line 24, in <module>
    from starlette.datastructures import UploadFile
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 7, in <module>
    from starlette.concurrency import run_in_threadpool
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 8, in <module>
    import anyio.to_thread
  File "/usr/local/lib/python3.10/dist-packages/anyio/__init__.py", line 27, in <module>
    from ._core._sockets import connect_tcp as connect_tcp
  File "/usr/local/lib/python3.10/dist-packages/anyio/_core/_sockets.py", line 35, in <module>
    from exceptiongroup import ExceptionGroup
ModuleNotFoundError: No module named 'exceptiongroup'

df: /root/.triton/autotune: No such file or directory

**Comment by ehsanahmadkhan525** [comment]
when i try to build an image from a dockerfile it gives this error i am just copying my models folder to the dockerfile evereything else is the same.

**Comment by erew123** [comment]
Hi @ehsanahmadkhan525 

I would like to draw your attention to the statement on the front page https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-docker-builds-and-google-colabs

![image](https://github.com/erew123/alltalk_tts/assets/35898566/862fc41d-b498-4287-b59a-e30947124309)

I am aware of various difficulties and issues with Docker builds as AllTalk has been updated over time. I am not a Docker expert and I'm focusing my attention updating AllTalk in a way that will ensure things are alleviated on Docker, Google colab etc as well as bring in new features.

That aside, I have updated the docker requirements file for you. This is for Nvidia systems only. You will need to update AllTalk on your system with a `git pull`

You can then on that system build a docker image with `docker build -t alltalk:v1-9c .` from within the AllTalk folder.

You can run the docker image with `docker-compose up -d` from within the AllTalk folder.

Stop it with `docker-compose stop`

View its logs with `docker-compose logs`

As mentioned this is for **Nvidia** based GPU systems. It takes a while to start up first time as it will compile DeepSpeed. I am not testing this in depth as I'm focused elsewhere for now.

Thanks

**Comment by ehsanahmadkhan525** [comment]
Thank you so much for the quick response I really appreciate it. You have helped me a lot. 
Best Regards
