### ISSUE TITLE
After finetune model - An error occurred: `penalty` has to be a strictly positive float, but is 7.0

### ISSUE THREAD

**Issue by IHaveAGenericUserName** [erew123/alltalk_tts#226]
After fine-tuning a model I receive an error when I try to generate new TTS regardless of if I use the newly trained model or not. 

An error occurred: `penalty` has to be a strictly positive float, but is 7.0
ERROR:    Exception in ASGI application

**To Reproduce**

- Install alltalk standalone, run start_alltalk.bat, verify it works to generate TTS.
- Exit alltalk, run start_finetune.bat
- Follow prompts to tune model, test model, compress and move model to a folder
- Exit finetune, run alltalk again
- Try to produce any tts and receive error.
- Reinstall alltalk in new directory, works fine. Move trained models over, works fine.
- 
**Screenshots**
![image](https://github.com/erew123/alltalk_tts/assets/16518889/06edb937-36a2-4c15-8d73-3ba16b861b4e)

**Text/logs**
`[AllTalk Model] Ready
[AllTalk TTSGen] Using API Local
 > Text splitted to sentences.
['AllTalk is a labour of love, developed and supported in my personal free time.', 'As such, my ability to respond to support requests is limited.', 'I prioritize issues based on their impact and the number of users affected.']
An error occurred: `penalty` has to be a strictly positive float, but is 7.0
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\responses.py", line 326, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'L:\\LLMs\\AllTalk\\alltalk_tts\\outputs\\undefined'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 77, in app
    await response(scope, receive, send)
  File "L:\LLMs\AllTalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\responses.py", line 329, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path L:\LLMs\AllTalk\alltalk_tts\outputs\undefined does not exist.`

**Desktop (please complete the following information):**
AllTalk was updated: Fresh install today
Custom Python environment: No
Text-generation-webUI was updated: today

**Comment by erew123** [comment]
Hi @IHaveAGenericUserName 

All fixed. Looks like the most recent version(s) of Transformers is demanding a float value. 

If you `git pull` the update https://github.com/erew123/alltalk_tts#-updating (no need to re apply the requirements), it should now for you.

BTW, you will get very slow generation using API Local, vs XTTS Local w/ DeepSpeed enabled.

Thanks
