### ISSUE TITLE
AllTalk v2 BETA Download Details & Discussion

### ISSUE THREAD

**Issue by zmarotrix** [erew123/alltalk_tts#318]
When I try to record audio in the Voice2RVC tab, it's always silent, and I get this error in the console: 

`ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\gradio\route_utils.py", line 714, in __call__
    await self.app(scope, receive, send)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 75, in app
    await response(scope, receive, send)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\responses.py", line 348, in __call__
    await send(
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\middleware\errors.py", line 161, in _send
    await send(message)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 510, in send
    output = self.conn.send(event=h11.EndOfMessage())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\h11\_writers.py", line 67, in __call__
    self.send_eom(event.headers, write)
  File "M:\AI\Voice\alltalk_tts\alltalk_environment\env\Lib\site-packages\h11\_writers.py", line 96, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length`

**Comment by erew123** [comment]
The error message is basically saying no data was sent over, aka, there is no audio.

Make sure you have allowed your microphone to be allowed as/when the message pops up on your browser e.g.

![image](https://github.com/user-attachments/assets/48fd1243-d29d-4242-a2d4-a71560e1f283)

Or use a site like this to check that your browser is giving access to your microphone https://www.onlinemictest.com/

Possibly try another web browser.

**Comment by zmarotrix** [comment]
Yes, I ensured it was enabled. I've also rested on both Opera, Chrome and Edge and it won't work. I've confirmed that my mic is working via https://mictests.com

**Comment by zmarotrix** [comment]
Okay, so I think I've figured it out. While this is still a bug, the reason it was not working was because I had the wrong default input device. The reason this is still a bug is because I selected my microphone from the drop down and it didn't work.

**Comment by erew123** [comment]
Hi @zmarotrix so are you telling me that you managed to get it working? 

Ultimately, any issue at this point of the process, is back to the Microphone, Windows OS setup for the Microphone and the web browser permissions/settings for allowing/selecting the microphone.

There is no actual code I have written to specifically handle a microphone, its literally a Gradio interface request to the web browser to allow the microphone to record audio. So if there is a bug, its either OS related or Gradio related, which will limit my ability to fix anything and it would be reliant on Gradio or Microsoft updating their code. So I am just wanting to clarify if you managed to get it working, should I get any other queries about this.
