### ISSUE TITLE
Not working on Windows 11 (installing beta version for the first time)

### ISSUE THREAD

**Issue by nitinmukesh** [erew123/alltalk_tts#347]
**Describe the bug**
Standalone install complete but the server is not starting

**To Reproduce**
Clone the beta version and complete the setup using atsetup.bat

**Screenshots**
N.A.

**Text/logs**

```
Microsoft Windows [Version 10.0.22631.4169]
(c) Microsoft Corporation. All rights reserved.

C:\tut\alltalk_tts>start_alltalk.bat
[AllTalk TTS]     _    _ _ _____     _ _       _____ _____ ____
[AllTalk TTS]    / \  | | |_   _|_ _| | | __  |_   _|_   _/ ___|
[AllTalk TTS]   / _ \ | | | | |/ _` | | |/ /    | |   | | \___ \
[AllTalk TTS]  / ___ \| | | | | (_| | |   <     | |   | |  ___) |
[AllTalk TTS] /_/   \_\_|_| |_|\__,_|_|_|\_\    |_|   |_| |____/
[AllTalk TTS]
[AllTalk TTS] Config file update: No Updates required
[AllTalk TTS] Start-up Mode     : Standalone mode
Traceback (most recent call last):
  File "C:\tut\alltalk_tts\system\config\firstrun.py", line 8, in <module>
    from inputimeout import inputimeout, TimeoutOccurred
ModuleNotFoundError: No module named 'inputimeout'
Error occurred while running the script: Command '['python', 'C:\\tut\\alltalk_tts\\system\\config\\firstrun.py']' returned non-zero exit status 1.
[AllTalk TTS] WAV file deletion : Disabled
[AllTalk TTS] Github updated    : 15th August 2024 at 08:27
Traceback (most recent call last):
  File "C:\tut\alltalk_tts\tts_server.py", line 147, in <module>
    from ffmpeg.asyncio import FFmpeg
ModuleNotFoundError: No module named 'ffmpeg'
[AllTalk TTS] Warning TTS Engine has NOT started up yet. Will keep trying for 240 seconds maximum. Please wait.
[AllTalk TTS] Warning Mechanical hard drives and a slow PCI BUS are examples of things that can affect load times.
[AllTalk TTS] Warning Some TTS engines index their AI TTS models on loading, which can be slow on CPU or old systems.
[AllTalk TTS] Warning Using one of the other TTS engines on slower systems can help ease this issue.
[AllTalk TTS]
[AllTalk TTS] Startup timed out. Full help available here https://github.com/erew123/alltalk_tts#-help-with-problems
[AllTalk TTS] On older systems, you may wish to open and edit script.py with a text editor and change the
[AllTalk TTS] startup_wait_time = 240 setting to something like startup_wait_time = 460 as this will allow
[AllTalk TTS] AllTalk more time (6 mins) to try load the model into your VRAM. Otherwise, please visit the GitHub for
[AllTalk TTS] a list of other possible troubleshooting options.
```

**Desktop (please complete the following information):**
AllTalk was updated: [approx. date] - using beta version and also git pull complete
Custom Python environment: [yes/no give details if yes] No
Text-generation-webUI was updated: [approx. date] N. A. as standalone install

**Additional context**
Log file
[diagnostics.log](https://github.com/user-attachments/files/17003353/diagnostics.log)

**Comment by nitinmukesh** [comment]
Additional steps completed after the above

```
(C:\tut\alltalk_tts\alltalk_environment\env) C:\tut\alltalk_tts>pip install inputimeout
Looking in indexes: https://pypi.org/simple/, https://pypi.ngc.nvidia.com
Collecting inputimeout
  Downloading inputimeout-1.0.4-py3-none-any.whl.metadata (2.2 kB)
Downloading inputimeout-1.0.4-py3-none-any.whl (4.6 kB)
Installing collected packages: inputimeout
Successfully installed inputimeout-1.0.4
```

**Comment by nitinmukesh** [comment]
Installation successful and server started and launched the UI.
