### ISSUE TITLE
Deepspeed installation errors. 

### ISSUE THREAD

**Issue by mercuryyy** [erew123/alltalk_tts#4]
Been trying to add Deepspeed as we really need that extra speed, on 4090 and want to be at around 400-700ms for 20 second audio files. 

On ubuntu 22.04

Followed alltalk_tts deepspeed instructions.

Getting the same error as - https://github.com/microsoft/DeepSpeed/discussions/3531

Tried adding "export CUDA_HOME=/usr/local/cuda" to start_linux.sh
but each time i re run start_linux.sh and then go to ./cmd_linux.sh

izzy@izzy-System-Product-Name:~/text-generation-webui$ ds_report

I get 

  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/izzy/text-generation-webui/installer_files/env/bin/nvcc'

If i post 

export CUDA_HOME=/usr/local/cuda

manually i still get - same error as - https://github.com/microsoft/DeepSpeed/discussions/3531

which is

  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/deepspeed/comm/comm.py", line 677, in mpi_discovery
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'

If i go 

./cmd_linux.sh
then post manually - export CUDA_HOME=/usr/local/cuda
then run
ds_report

i get

`
```
izzy@izzy-System-Product-Name:~/text-generation-webui$ ./cmd_linux.sh
(/home/izzy/text-generation-webui/installer_files/env) izzy@izzy-System-Product-Name:~/text-generation-webui$ export CUDA_HOME=/usr/local/cuda
(/home/izzy/text-generation-webui/installer_files/env) izzy@izzy-System-Product-Name:~/text-generation-webui$ ds_report
[2023-12-17 09:13:30,168] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch']
torch version .................... 2.1.2+cu121
deepspeed install path ........... ['/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/deepspeed']
deepspeed info ................... 0.12.5, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version ..................... 12.3
deepspeed wheel compiled w. ...... torch 2.1, cuda 12.1
shared memory (/dev/shm) size .... 15.54 GB
(/home/izzy/text-generation-webui/installer_files/env) izzy@izzy-System-Product-Name:~/text-generation-webui$ 
izzy@izzy-System-Product-Name:~/text-generation-webui$ ./cmd_linux.sh
(/home/izzy/text-generation-webui/installer_files/env) izzy@izzy-System-Product-Name:~/text-generation-webui$ export CUDA_HOME=/usr/local/cuda
(/home/izzy/text-generation-webui/installer_files/env) izzy@izzy-System-Product-Name:~/text-generation-webui$ ds_report
[2023-12-17 09:13:30,168] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch']
torch version .................... 2.1.2+cu121
deepspeed install path ........... ['/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/deepspeed']
deepspeed info ................... 0.12.5, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version ..................... 12.3
deepspeed wheel compiled w. ...... torch 2.1, cuda 12.1
shared memory (/dev/shm) size .... 15.54 GB
(/home/izzy/text-generation-webui/installer_files/env) izzy@izzy-System-Product-Name:~/text-generation-webui$ izzy@izzy-System-Product-Name:~/text-generation-webui$ ./cmd_linux.sh
(/home/izzy/text-generation-webui/installer_files/env) izzy@izzy-System-Product-Name:~/text-generation-webui$ export CUDA_HOME=/usr/local/cuda
(/home/izzy/text-generation-webui/installer_files/env) izzy@izzy-System-Product-Name:~/text-generation-webui$ ds_report
[2023-12-17 09:13:30,168] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch']
torch version .................... 2.1.2+cu121
deepspeed install path ........... ['/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/deepspeed']
deepspeed info ................... 0.12.5, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version ..................... 12.3
deepspeed wheel compiled w. ...... torch 2.1, cuda 12.1
shared memory (/dev/shm) size .... 15.54 GB
(/home/izzy/text-generation-webui/installer_files/env) izzy@izzy-System-Product-Name:~/text-generation-webui$
```

**Comment by erew123** [comment]
In the text-generation-webui folder, if you do ./cmd_linux.sh and **then** check your environment variables is CUDA_HOME still set to the correct path?

**Comment by mercuryyy** [comment]
Only if i run it manually like

./cmd_linux.sh
then post manually - export CUDA_HOME=/usr/local/cuda
then run
ds_report

i get the "Above report" i updated the the post

but then if run 

./start_linux.sh

it goes back to 

```
File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/subprocess.py", line 1026, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/subprocess.py", line 1950, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/izzy/text-generation-webui/installer_files/env/bin/nvcc'
```

**Comment by erew123** [comment]
So this is text-generation-webui's custom python environment over-writing your environment variables, which is normal. 

You should be able to `./cmd_linux.sh` set your environment `export CUDA_HOME=/usr/local/cuda` and then `python server.py`

Which should at least get it started with deepspeed.

To change the environment variable permanently inside of a conda python environment https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#set-env-vars so that you could just `./start_linux.sh`

I believe its linked to the above. Though I cannot say if there are other implications to text-generation-webui and permanently changing the environment variable. I havnt noticed any myself, but Im just giving fair warning. I cannot for the life of me remember the exact file/change/command to permanently change the environment variable in conda/text-generation-webui and I dont have a Linux machine to hand on me right now.

**Comment by mercuryyy** [comment]
Thank loading it with ./cmd_linux.sh and then python_server.py did load deepspeed it said "detected"

But now im not able to load the LLM getting

```
Running on local URL:  http://0.0.0.0:7860
Traceback (most recent call last):
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/modules/chat.py", line 407, in redraw_html
    return chat_html_wrapper(history, name1, name2, mode, style, character, reset_cache=reset_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/modules/html_generator.py", line 308, in chat_html_wrapper
    return generate_cai_chat_html(history['visible'], name1, name2, style, character, reset_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/modules/html_generator.py", line 232, in generate_cai_chat_html
    row = [convert_to_markdown(entry) for entry in _row]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/modules/html_generator.py", line 232, in <listcomp>
    row = [convert_to_markdown(entry) for entry in _row]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/modules/html_generator.py", line 52, in convert_to_markdown
    string = re.sub(r'(^|[\n])&gt;', r'\1>', string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/modules/chat.py", line 407, in redraw_html
    return chat_html_wrapper(history, name1, name2, mode, style, character, reset_cache=reset_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/modules/html_generator.py", line 308, in chat_html_wrapper
    return generate_cai_chat_html(history['visible'], name1, name2, style, character, reset_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/modules/html_generator.py", line 232, in generate_cai_chat_html
    row = [convert_to_markdown(entry) for entry in _row]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/modules/html_generator.py", line 232, in <listcomp>
    row = [convert_to_markdown(entry) for entry in _row]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/modules/html_generator.py", line 52, in convert_to_markdown
    string = re.sub(r'(^|[\n])&gt;', r'\1>', string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
2023-12-17 09:32:43 INFO:Loading mistralai_Mistral-7B-Instruct-v0.2...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:04<00:00,  1.63s/it]
2023-12-17 09:32:48 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/home/izzy/text-generation-webui/modules/ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/modules/models.py", line 89, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izzy/text-generation-webui/modules/models.py", line 173, in huggingface_loader
    model = deepspeed.initialize(model=model, config_params=ds_config, model_parameters=None, optimizer=None, lr_scheduler=None)[0]
            ^^^^^^^^^
NameError: name 'deepspeed' is not defined
```

**Comment by mercuryyy** [comment]
So i am probably getting the above because when i run

(/home/izzy/text-generation-webui/installer_files/env) izzy@izzy-System-Product-Name:~/text-generation-webui$ python server.py --listen --listen-port 7860 --force-safetensors --api --trust-remote --extensions alltalk_tts --deepspeed

I again get the mpi4y error

```

izzy@izzy-System-Product-Name:~/text-generation-webui$ ./cmd_linux.sh
(/home/izzy/text-generation-webui/installer_files/env) izzy@izzy-System-Product-Name:~/text-generation-webui$ export CUDA_HOME=/usr/local/cuda
(/home/izzy/text-generation-webui/installer_files/env) izzy@izzy-System-Product-Name:~/text-generation-webui$ python server.py --listen --listen-port 7860 --force-safetensors --api --trust-remote --extensions alltalk_tts --deepspeed
2023-12-17 09:38:11 WARNING:trust_remote_code is enabled. This is dangerous.
2023-12-17 09:38:11 WARNING:
You are potentially exposing the web UI to the entire internet without any access password.
You can create one with the "--gradio-auth" flag like this:

--gradio-auth username:password

Make sure to replace username:password with your own.
[2023-12-17 09:38:12,536] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2023-12-17 09:38:12,712] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-12-17 09:38:12,712] [INFO] [comm.py:652:init_distributed] Not using the DeepSpeed or dist launchers, attempting to detect MPI environment...
Traceback (most recent call last):
  File "/home/izzy/text-generation-webui/server.py", line 35, in <module>
    from modules import (
  File "/home/izzy/text-generation-webui/modules/chat.py", line 20, in <module>
    from modules.text_generation import (
  File "/home/izzy/text-generation-webui/modules/text_generation.py", line 24, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/home/izzy/text-generation-webui/modules/models.py", line 49, in <module>
    deepspeed.init_distributed()
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/deepspeed/comm/comm.py", line 658, in init_distributed
    mpi_discovery(distributed_port=distributed_port, verbose=verbose)
  File "/home/izzy/text-generation-webui/installer_files/env/lib/python3.11/site-packages/deepspeed/comm/comm.py", line 677, in mpi_discovery
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
```

**Comment by erew123** [comment]
Ah, for AllTalk, you dont need to specify the --deepspeed. That flag is for Text-generation-webui its self and its model loaders (which is what your error is related to). I've never tried that flag with text-gen, so I have no frame of reference.

https://github.com/oobabooga/text-generation-webui?tab=readme-ov-file#deepspeed

You may want to remove the --deepspeed flag and check things work. They should do. If you want to use deepspeed specifically with text-gen-webui, you might want to check over the wiki or issues there and see how that works. But you definitely dont need that flag on for alltalk to use deepspeed.

**Comment by mercuryyy** [comment]
[AllTalk TTSGen] 0.81 seconds. LowVRAM: False DeepSpeed: True

All seems to work, great thanks again very good implementation and instructions great extension!

You should really look into add piper - https://github.com/rhasspy/piper

I think after their recent update they beat Coqui out of the park, both in speed and quality.

**Comment by erew123** [comment]
Glad its working! :) And, other TTS's.... yeah Im thinking of adding others, once Im truly happy the base of this one is in place.
