### ISSUE TITLE
Why do i see these errors sometimes in the All Talk console ?

### ISSUE THREAD

**Issue by Tum1370** [erew123/alltalk_tts#472]
Why do i see these errors appering in the All Talk console window ?
They do not seem to affect anything, am just wondering what they are, is it something am doing wrong ? Is it a memory problem ?

_ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "M:\Software\AI_Tools\alltalk_tts\alltalk_tts\alltalk_environment\env\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "M:\Software\AI_Tools\alltalk_tts\alltalk_tts\alltalk_environment\env\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host_

**Comment by erew123** [comment]
@Tum1370 Are you using V1 of AllTalk? Ive not seen that message for quite some time now.

I had it listed here https://github.com/erew123/alltalk_tts?tab=readme-ov-file#configuration-and-usage-issues

The issue is only seen on Windows and typically with Chrome based browsers. Its also nothing more than an annoyance. There are many examples of people complaining about it on the internet e.g. https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7524

Its not a memory issue, its to do with asynchronous events occurring between sub-processes and  a disconnect/reconnect of the session occurring from the web browser (best I can understand). It is nothing more than an annoying error message that looks pretty horrific on the screen, but is really just telling you Windows/Web-browsers disconnected and re-connected the session to the back end while a sub-process was running.

I hadnt see it for a while now, so I assumed it was resolved by Python and they had cleared up the message... at least, Ive not seen it occur in AllTalk V2, only V1. Let me know and I can at least update the wiki

**Comment by Tum1370** [comment]
HI, Am using AllTalk v2, I installed the standalone version about 2 weeks ago, and copied the extension folder to oobabooga's extensions folder. I use Microsoft Edge browser on windows 11. I have the oobabooga webui setup as a APP from Microsoft Edge.
THe errors is see are always in the AllTalk console window.
Here is a screenshot of my AllTalk console just after i start  it.
Maybe you can see something wrong on it ?

![image](https://github.com/user-attachments/assets/f46d224d-56e0-408f-8c2c-7e6e0be9636c)

**Comment by Tum1370** [comment]
Just as an addition, Now everytime i load up AllTalk, the console now spams these error messages.
Is it somethng to do with what chat is on the oobabooga platform ?

**Comment by erew123** [comment]
It probably is something to do with Ooobabooga and external calls occurring. Whilst its not anything more than a whinge, I may be able to clear them up. Is it specifically with the XTTS engine you are using/seeing the issues (just so I can try and re-create at my end). 

Thanks

**Comment by Tum1370** [comment]
Thats tha only engine i do use presently.

**Comment by erew123** [comment]
@Tum1370 Im working my way through some PR's that people have submitted, which may take me a few days. As they change some of the engines behaviour I dont want to do multiple code updates that overlap, but when I have those in, I probably can do something to silence that message/hide it from the console.... so give me a few days and Ill try confirm back to you.

**Comment by Tum1370** [comment]
Great, thank you for the update.
