### ISSUE TITLE
Finetuning: AssertionError if the filename of the input sound clip in the `/finetune` folder has a number in it.

### ISSUE THREAD

**Issue by vrmuza** [erew123/alltalk_tts#55]
**EDIT: This is not the root cause. There's something else causing it**

**Platform**
Windows 10

**Commit**
50aa6de

**Describe the bug**
The `metadata_train.csv` and `metadata_eval.csv` files do not get populated with the filenames from `/finetune/tmp-trn/wavs`, preventing the training workflow from continuing. 

`/finetune/put-voice-samples-in-here/boy2_dirty.wav` = Fail
`/finetune/put-voice-samples-in-here/boya_dirty.wav` = Works

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a number to the filename of the sample file.
2. Run "Step 1" of the finetune trainer
3. If "Step 2" of the finetune trainer is run, an error will occur due to the empty csvs

**Screenshots**
![1 Screenshot 2024-01-09 173708](https://github.com/erew123/alltalk_tts/assets/134181330/a51c3193-e6c6-4d5a-bae2-7b91dbb0c59f)
![2 Screenshot 2024-01-09 173915](https://github.com/erew123/alltalk_tts/assets/134181330/53e66628-9640-4cd3-9a74-c94a680918f1)

**Text/logs**
```
(test_env) P:\voice\alltalk_tts>python finetune.py
Running on local URL:  http://127.0.0.1:7052
[FINETUNE] HTTP Request: GET http://127.0.0.1:7052/startup-events "HTTP/1.1 200 OK"
[FINETUNE] HTTP Request: HEAD http://127.0.0.1:7052/ "HTTP/1.1 200 OK"

To create a public link, set `share=True` in `launch()`.
[FINETUNE] HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
[FINETUNE] HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 OK"
[FINETUNE] HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 OK"
[FINETUNE] HTTP Request: POST https://api.gradio.app/gradio-initiated-analytics/ "HTTP/1.1 200 OK"
[FINETUNE] HTTP Request: POST https://api.gradio.app/gradio-launched-telemetry/ "HTTP/1.1 200 OK"
[FINETUNE] Part of AllTalk https://github.com/erew123/alltalk_tts/
[FINETUNE] Coqui Public Model License
[FINETUNE] https://coqui.ai/cpml.txt
[FINETUNE] Starting Step 1 - Preparing Audio/Generating the dataset
[FINETUNE] Updated lang.txt with the target language.
[FINETUNE] Loading Whisper Model: large-v3
[FINETUNE] Current working file: P:\voice\alltalk_tts\finetune\put-voice-samples-in-here\boy2_dirty.wav
[FINETUNE] Processing audio with duration 04:21.649
[FINETUNE] VAD filter removed 00:11.792 of audio
[FINETUNE] Train CSV: P:\voice\alltalk_tts\finetune\tmp-trn\metadata_train.csv
[FINETUNE] Eval CSV: P:\voice\alltalk_tts\finetune\tmp-trn\metadata_eval.csv
[FINETUNE] Audio Total: 261.6491458333333
[FINETUNE] Dataset Generated. Move to Step 2
[FINETUNE] Starting Step 2 - Fine-tuning the XTTS Encoder
[FINETUNE] Starting finetuning on Base Model
>> DVAE weights restored from: P:\voice\alltalk_tts\models\xttsv2_2.0.2\dvae.pth
Traceback (most recent call last):
  File "P:\voice\alltalk_tts\finetune.py", line 1091, in train_model
    config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=str(output_path), max_audio_length=max_audio_length)
  File "P:\voice\alltalk_tts\finetune.py", line 422, in train_gpt
    train_samples, eval_samples = load_tts_samples(
  File "P:\voice\alltalk_tts\test_env\lib\site-packages\TTS\tts\datasets\__init__.py", line 121, in load_tts_samples
    assert len(meta_data_train) > 0, f" [!] No training samples found in {root_path}/{meta_file_train}"
AssertionError:  [!] No training samples found in P:\voice\alltalk_tts\finetune\tmp-trn/P:\voice\alltalk_tts\finetune\tmp-trn\metadata_train.csv
```

**Comment by vrmuza** [comment]
Unrelated to filename. It's an issue with Whisper that I cannot reproduce.

**Comment by erew123** [comment]
Oh.. interesting! Glad you sorted it! And thanks for closing the ticket/solving it.. one less problem for me to deal with today! haha
